version: 1.0.{build}
nuget:
  account_feed: true
  project_feed: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key: f9e66dfa-7351-411c-8c45-f0ace1e3ce9b
  secure: m49OJ7+Jdt9an3jPcTukHA==
  skip_symbols: false
  artifact: /.*\.nupkg/