version: 1.0.{build}
nuget:
  account_feed: true
  project_feed: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
artifacts:
- path: CIProject\\ConsoleApplication8\ClassLibrary1\bin\Debug\ClassLibrary1.dll
  name: TestPkg
deploy:
- provider: NuGet
  api_key:
    secure: enE8vH/KrUPkw93oNo9W86kaX+gsgWZxUdhCmp4j3/+dW3mQphZOq1JrsOHUBegs